# database connection
[connections.postgresql]
dialect = "postgresql+psycopg2"
host = "localhost"
port = "5432"
database = "skill_score"
username = "postgres"
password = "3RJI;F=PLo#u"

# mail service
[connections.smtp]
host = "smtp.gmail.com"
port = "465"
email = "skillscore.community@gmail.com"
password = "jcjt auts oxle hbhu"

